<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Observer</AssemblyName>
    <RootNamespace>Observer</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="transport-model.json" LogicalName="Observer.transport-model.json" />
    <None Include="yolox_nano.onnx" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <None Include="licenses/**" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.22.0" />
  </ItemGroup>
</Project>
